version: '3.7'

services: 
  # postgres:
  #   container_name: postgres
  #   image: postgres:13.1
  #   restart: always
  #   ports: 
  #     - "5432:5432"
  #   volumes: 
  #     - ./pgdata:/var/lib/postgresql/data
  #   networks: 
  #     - devopsnet
  #   environment: 
  #     - POSTGRES_PASSWORD=postgres14
  #     - POSTGRES_USER=tommy14
  #     - POSTGRES_DB=product
  
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports: 
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   restart: unless-stopped
  #   networks: 
  #     - devopsnet
  #   depends_on: 
  #     - postgres

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks: 
      - devopsnet
    # depends_on: 
    #   - postgres

  nodejs: 
    image: mtommyp14/back:main
    restart: always
    ports: 
      - 9291-9294:9291
    env_file: 
      - ./back/.env
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
    environment: 
      - DBUSER=admin
      - DBPASSWORD=abcd1234
      - DBNAME=coffeshop
      - DBHOST=3.83.153.65
      - DBPORT=5432
      - JWT_KEYS=CoffeShopSecret
      - CLOUD_KEY=714179943541359
      - CLOUD_SECRET=loGg2aExEh29n57efZGzcsbiwQk
      - CLOUD_NAME=coffeshopdevops
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
    depends_on: 
      # - postgres
      # - pgadmin
      - redis
    networks: 
      - devopsnet

networks: 
  devopsnet: